apiVersion: v1
kind: Service
metadata:
  name: capture-worker
  labels:
    app: capture
spec:
  ports:
  - port: 80
    name: dummy
  clusterIP: None
  selector:
    app: capture
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: capture-worker
spec:
  serviceName: "capture-worker"
  replicas: 3
  ordinals:
    start: 1
  selector:
    matchLabels:
      app: capture
  template:
    metadata:
      labels:
        app: capture
    spec:
      nodeSelector:
        role: capture
      containers:
        - name: capture
          image: video-capture:latest
          imagePullPolicy: IfNotPresent
          command: ["python3", "-u", "src/capture/main.py"]
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: RTSP_BASE_URL
              value: "rtsp://admin:hanta123$@202.31.34.211:558/LiveChannel/"
            - name: BUFFER_DURATION
              value: "2"
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: videos-volume
              mountPath: /videos
            - name: src-volume
              mountPath: /app/src/capture
      volumes:
      - name: shm
        emptyDir: {}
      - name: videos-volume
        hostPath:
          path: /videos
          type: Directory
      - name: src-volume
        hostPath:
          path: /home/jungg/workspace/safety-hanta/src/capture
          type: Directory
