apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-redis.yaml
  - 02-rtsp-sim.yaml
  - capture-worker-1-deployment.yaml
  - capture-worker-2-deployment.yaml
  - 04-inference.yaml
