apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-redis.yaml
  - 02-rtsp-sim.yaml
  - 03-capture-worker-deployment.yaml
  - 04-inference.yaml
  - nvidia-runtime-class.yaml
  - nvidia-device-plugin.yaml
  - sysctl-fix.yaml
